version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./back
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./back:/code
    ports:
      - "8000:8000"
    env_file:
      - ./back/.env
    depends_on:
      - db

  frontend:
    build: ./front
    ports:
      - "5173:5173"
    env_file:
      - ./front/.env
    depends_on:
      - backend